ci: setting GO111MODULE=on for Setup Tools step

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -13,8 +13,35 @@ jobs:
       - name: Setup Tools
         env:
           # GO111MODULE: on
-          GOPATH: /home/runner/work/
         run: |
-          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
           # go get github.com/ahmetb/govvv
-          ls -la /home/runner/work/bin/
+          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
+      - name: Check out Code
+        uses: actions/checkout@v1
+      - name: Install Dependencies
+        run: go mod download
+      - name: Lint
+        env:
+          GOPATH: /home/runner/work
+        run: ${GOPATH}/bin/golangci-lint run
+        # continue-on-error: true
+      - name: Unit Test
+        run: make test
+      # - name: Integration Test
+      #   run: make inte
+      - name: Upload coverage to Codecov
+        # -U "--proxy http://http-proxy"
+        run: bash <(curl -s https://codecov.io/bash)
+          -F unittests
+          -n codecov-micros
+          -f ./build/coverage.txt
+          -B "${GITHUB_REF//refs\/heads\//}"
+          -T "${GITHUB_REF//refs\/tags\//}"
+          -C "${GITHUB_SHA}"
+          -Z || echo 'Codecov upload failed'
+        env:
+          CI: true
+          CODECOV_ENV: github-action
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+          CODECOV_PR: ${{ github.event.after }}
+          CODECOV_SHA: ${{ github.sha }}
